name: node-setup
on:
 push:
  branches:
   - master
 workflow_dispatch:   
jobs:
 setup:
  runs-on: ubuntu-latest
  steps:
   - name: node version check
     run: node -v
   - uses: actions/node-setup@v1
     with:
       node: 16 
