name: node-setup

on:
 push:
  branches:
   - master
 pull_request:
   types: [clossed,opened, reopened,assigned] 
# schedule:
#   - cron: "0 0 * * *"
 workflow_dispatch:
 
jobs:
 setup:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v2.7.0
   - name: files lists
     run: |
      ls -a
      pwd
      echo $GITHUB_REPOSITORY
      echo $GITHUB_WORKSPACE
   - name: node version check
     id: node
     run: node -v
   - uses: actions/setup-node@v2.5.2
     with:
       node-version: 16.x
   - name: output
     run: echo "${{ steps.node.outputs.time }}"
   - name: Notify dedicated teams channel
     if: ${{ success() }}
     uses: jdcargile/ms-teams-notification@v1.3
     with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
          notification-summary: github-actions workflow triggered by Bhavya 
          notification-color: 17a2b8
          timezone: Asia/Kolkata  
